export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';

export const GET_BLOCK_NODE_STATUS_START = 'GET_BLOCK_NODE_STATUS_START';
export const GET_BLOCK_NODE_STATUS_FAILURE = 'GET_BLOCK_NODE_STATUS_FAILURE';
export const GET_BLOCK_NODE_STATUS_SUCCESS = 'GET_BLOCK_NODE_STATUS_SUCCESS';
