export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';

export const RETRIEVE_BLOCKS_START = 'RETRIEVE_BLOCKS_START';
export const RETRIEVE_BLOCKS_SUCCESS = 'RETRIEVE_BLOCKS_SUCCESS';
export const RETRIEVE_BLOCKS_FAILURE = 'RETRIEVE_BLOCKS_FAILURE';
