export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';

export const FETCH_BLOCK_STATUS_START = 'FETCH_BLOCK_STATUS_START';
export const FETCH_BLOCK_STATUS_SUCCESS = 'FETCH_BLOCK_STATUS_SUCCESS';
export const FETCH_BLOCK_STATUS_FAILURE = 'FETCH_BLOCK_STATUS_FAILURE';
